replicaCount: 1

image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: '1.4'
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: 'nginx'
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix

env:
  - name: PASSWORD
    valueFrom:
      secretKeyRef:
        name: metrics-app-secret
        key: password
